apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "common.labels" . | nindent 4 }} 
spec:
  selector: {{ include "common.labels" . | nindent 4 }} 
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    protocol: TCP
